load("//research/colab:build_defs.bzl", "colab_binary")

colab_binary(
    name = "normals_from_volume",
    python_version = "PY3",
    deps = [
        "//experimental/users/xiuming/sim/sim/datasets",
        "//experimental/users/xiuming/sim/sim/models",
        "//experimental/users/xiuming/sim/sim/util",
        "//experimental/users/xiuming/xiuminglib",
        "//file/colossus/cns",
        "//pyglib:gfile",
        "//third_party/py/cvx2",
        "//third_party/py/numpy",
        "//third_party/py/plotly",
        "//third_party/py/tensorflow",
    ],
)
