py_binary(
    name = "vs_jaxnerf",
    srcs = ["vs_jaxnerf.py"],
    python_version = "PY3",
    deps = [
        "//experimental/users/xiuming/xiuminglib",
        "//pyglib:gfile",
        "//third_party/py/IPython:ipython-libs",
        "//third_party/py/absl:app",
        "//third_party/py/numpy",
        "//third_party/py/tqdm",
    ],
)
