py_binary(
    name = "main",
    srcs = ["main.py"],
    python_version = "PY3",
    deps = [
        "//experimental/users/xiuming/xiuminglib",
        "//file/colossus/cns",
        "//pyglib:gfile",
        "//third_party/py/IPython:ipython-libs",
        "//third_party/py/tqdm",
    ],
)
