py_binary(
    name = "relight_fig",
    srcs = ["relight_fig.py"],
    python_version = "PY3",
    deps = [
        "//experimental/users/xiuming/sim/eval:util",
        "//experimental/users/xiuming/xiuminglib",
        "//file/colossus/cns",
        "//pyglib:gfile",
        "//third_party/py/IPython:ipython-libs",
        "//third_party/py/numpy",
        "//third_party/py/tqdm",
    ],
)
