py_binary(
    name = "microfacet",
    srcs = ["microfacet.py"],
    python_version = "PY3",
    deps = [
        "//experimental/users/xiuming/sim/sim/datasets",
        "//experimental/users/xiuming/sim/sim/models",
        "//experimental/users/xiuming/sim/sim/util",
        "//pyglib:gfile",
        "//third_party/py/IPython:ipython-libs",
        "//third_party/py/absl:app",
        "//third_party/py/tensorflow",
        "//third_party/py/tqdm",
    ],
)
