py_library(
    name = "renderer",
    srcs = ["renderer.py"],
    deps = [
        "//experimental/users/xiuming/xiuminglib",
        "//third_party/py/IPython:ipython-libs",
        "//third_party/py/numpy",
    ],
)
