py_binary(
    name = "main",
    srcs = ["main.py"],
    python_version = "PY3",
    deps = [
        "//file/colossus/cns",
        "//pyglib:gfile",
        "//third_party/py/IPython:ipython-libs",
        "//third_party/py/absl:app",
        "//third_party/py/tensorflow",
        "//third_party/py/tensorflow:tensorflow_google",
        "//third_party/py/tqdm",
    ],
)
