py_binary(
    name = "make_dataset",
    srcs = ["make_dataset.py"],
    python_version = "PY3",
    deps = [
        "//experimental/users/xiuming/sim/brdf:renderer",
        "//experimental/users/xiuming/sim/data_gen:util",
        "//experimental/users/xiuming/xiuminglib",
        "//file/colossus/cns",
        "//pyglib:gfile",
        "//third_party/py/IPython:ipython-libs",
        "//third_party/py/absl:app",
        "//third_party/py/numpy",
        "//third_party/py/tqdm",
    ],
)
