py_library(
    name = "util",
    srcs = glob([
        "*.py",
    ]),
    deps = [
        "//experimental/users/xiuming/xiuminglib/xiuminglib",
        "//file/colossus/cns",
        "//learning/deepmind/video/python:video_api",
        "//pyglib:gfile",
        "//third_party/py/IPython:ipython-libs",
        "//third_party/py/PIL:pil",
        "//third_party/py/absl/logging",
        "//third_party/py/matplotlib",
        "//third_party/py/numpy",
        "//third_party/py/scipy",
        "//third_party/py/tensorflow",
        "//vision/sfm:protolib_py_pb2",
        "//vision/sfm/wrappers/python",
        "//vision/sfm/wrappers/python:camera",
        "//vr/kenobi/deep_holo:over_ops",
    ],
)
