py_library(
    name = "networks",
    srcs = glob([
        "*.py",
    ]),
    deps = [
        "//experimental/users/xiuming/sim/sim/util",
        "//pyglib:gfile",
        "//third_party/py/IPython:ipython-libs",
        "//third_party/py/numpy",
        "//third_party/py/tensorflow",
    ],
)
