py_library(
    name = "models",
    srcs = glob([
        "*.py",
    ]),
    deps = [
        "//experimental/users/xiuming/sim/brdf:renderer",
        "//experimental/users/xiuming/sim/brdf/merl",
        "//experimental/users/xiuming/sim/brdf/microfacet",
        "//experimental/users/xiuming/sim/sim:losses",
        "//experimental/users/xiuming/sim/sim/networks",
        "//experimental/users/xiuming/sim/sim/util",
        "//experimental/users/xiuming/xiuminglib",
        "//third_party/py/IPython:ipython-libs",
        "//third_party/py/numpy",
        "//third_party/py/tensorflow",
        "//third_party/py/tqdm",
    ],
)
