py_binary(
    name = "calc_buf",
    srcs = ["calc_buf.py"],
    python_version = "PY3",
    deps = [
        "//experimental/users/xiuming/sim/brdf:renderer",
        "//experimental/users/xiuming/sim/sim/datasets",
        "//experimental/users/xiuming/sim/sim/models",
        "//experimental/users/xiuming/sim/sim/util",
        "//experimental/users/xiuming/xiuminglib",
        "//file/colossus/cns",
        "//pyglib:gfile",
        # "//third_party/py/cvx2",
        "//third_party/py/numpy",
        "//third_party/py/tensorflow",
        "//pipeline/flume/py:runner",
        "//third_party/py/apache_beam",
    ],
)
